// Generated by https://quicktype.io

export interface Usuario {
    albumId:      number;
    id:           number;
    title:        string;
    Descripcion:  string;
    thumbnailUrl: string;
}
